商品一覧を表示する機能の追加
kitazawasyogo/shopping-cart pull request #2
Opened 2023-03-16 23:48 UTC by kitazawasyogo

@nabemasamasa　@Takatatsu9

**商品一覧を表示する機能の追加**を行いました。

不足している部分やより良い書き方があれば教えていただきたいです。
お忙しいところ恐れ入りますがレビューお願いいたします。

2023-03-17 01:28 UTC, nabemasamasa reviewed
done

2023-03-17 01:28 UTC, nabemasamasa commented on ShoppingCart.Test/InputValueValidatorTest.vb
> +        Catch expected As ArgumentException
[Q] 「例外を投げない」テストですが、万が一コードにミスがあって、ArgumentExceptionが発生した場合、このテストメソッドってどうなりますか？
試しに、SelectFeaturesメソッド内で必ずArgumentExceptionが発生するようにして、確認してみてほしいです。

2023-03-17 01:28 UTC, nabemasamasa commented on ShoppingCart/MerchandiseList.vb
> +        Console.Write($"{stockItem}")
[imo] 区切り文字Spaceに応じて、Join使った方が楽そう。`Join({nameItem,descriptionItem,priceItem,stokeItem}, Space(1))`

2023-03-17 01:28 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +        ElseIf inputOption(0).Equals("list") AndAlso inputOption.Length = INPUT_VALUE_LENGTH And input.Contains("--sort price") Then
[Q] AndとAndAlsoの違いって理解してますか？

2023-03-17 01:28 UTC, nabemasamasa commented on ShoppingCart.Test/OptionalFeaturesTest.vb
> +    Public Sub 商品名で検索した商品の情報を返すか(searchName As String)
[nits] 見つからない場合のテストも欲しいです

2023-03-17 01:28 UTC, nabemasamasa commented on ShoppingCart/OptionalFeatures.vb
> +    Public Function RemoveByName(searchName As String, list As List(Of Merchandise)) As List(Of Merchandise)
メソッド名がRemoveでByName…訳すと「名前で除外する」なんだけど、実際には引数で指定した名前以外を除外する。メソッド名もそうなんだけど、コメントもコメントで「引数外の商品を除外する」とはわからない。

[Q] 「抽出する」とか「絞り込む」とか「検索する」でメソッド名つける方が適切だと思いますが、どう思いますか？

2023-03-17 01:28 UTC, nabemasamasa commented on ShoppingCart.Test/OptionalFeaturesTest.vb
> +    <Test()> Public Sub 価格の範囲で検索した商品の情報を返すか()
[nits] 範囲にない場合のテストが欲しい

2023-03-17 01:28 UTC, nabemasamasa commented on ShoppingCart.Test/OptionalFeaturesTest.vb
> +    <Test()> Public Sub 価格の範囲で検索した商品の情報を返すか()
[nits] 条件がおかしい場合のテストがほしい
=> 範囲じゃない(`searchPriceRange  = "100"`とか`"-200"`だったり)、数値じゃない(`abc-200`)

2023-03-17 01:28 UTC, nabemasamasa commented on ShoppingCart.Test/OptionalFeaturesTest.vb
> +        Assert.That(actual, [Is].EqualTo(("--name 名前:商品名の曖昧一致検索を行えます。" & vbCrLf & "--price 価格-価格:指定した価格内に収まる商品の検索を行えます。" & vbCrLf & "--sort name:商品一覧を商品名の昇順に並び替える事が出来ます。" & vbCrLf & "--sort price:商品一
[nits] `vbcrlf`でソースコードも改行した方が見やすい……

2023-03-17 01:28 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +        product.DisplayMerchandiseList(productList)
インデントおかしい

2023-03-17 01:28 UTC, nabemasamasa commented on ShoppingCart/OptionalFeatures.vb
> +            displayHelpMessage = "--name 名前:商品名の曖昧一致検索を行えます。" & vbCrLf & "--price 価格-価格:指定した価格内に収まる商品の検索を行えます。" & vbCrLf & "--sort name:商品一覧を商品名の昇順に並び替える事が出来ます。" & vbCrLf & "--sort price:商品一覧を価格の昇順に並
[imo] すぐReturnさせる方が好みだな…… `displayHelpMessage`定義しなくても良くなるし

2023-03-17 01:28 UTC, nabemasamasa commented on ShoppingCart/OptionalFeatures.vb
> +            displayHelpMessage = "--name 名前:商品名の曖昧一致検索を行えます。" & vbCrLf & "--price 価格-価格:指定した価格内に収まる商品の検索を行えます。" & vbCrLf & "--sort name:商品一覧を商品名の昇順に並び替える事が出来ます。" & vbCrLf & "--sort price:商品一覧を価格の昇順に並
[imo] `vbCrlf`でコードも改行した方が見やすいし、行削除したり行追加するだけでコマンド増減できるから楽そう。

2023-03-17 01:28 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +            masserge = "もしかして：list --help"
マッサージ

2023-03-17 01:28 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +        ElseIf inputOption(0).Equals("list") AndAlso inputOption(1).Contains("na") Then
[nits] `list`のオプションのサジェストするのに毎回`inputOption(0).Equals("list")`してるの煩わしいな……。
これはNestした方がいいんじゃない？

2023-03-17 01:28 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +        ElseIf inputOption(0).Contains("he") Then
もしかして：`uhe`でも`help`をサジェストしてくれる

2023-03-17 01:28 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +            masserge = "もしかして：list --price 価格-価格"
[imo] 私なら、最初から`message`に`もしかして：`を設定して適宜結合する。
で、そうすると何も引っかからない場合`もしかして：`だけ返しちゃうから、Elseを追加して`Return Nothing`させる

2023-03-17 01:28 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +            product.DisplayMerchandiseList(productList)
と思ったら、直ってる。Pushする前にこの差分だけ移せたのでは？？？

2023-03-17 01:29 UTC, nabemasamasa commented
テストコケてるのに、MergePullRequestボタンが有効になってる……
確認してほしいです。

2023-03-17 01:57 UTC, Takatatsu9 reviewed
Done

2023-03-17 01:57 UTC, Takatatsu9 commented on ShoppingCart/MerchandiseList.vb
> +    Private ReadOnly nameItem As String = "商品名"
[Q] 定数にしてませんけど、書き換える予定でもあるんですか？

2023-03-17 01:57 UTC, Takatatsu9 commented on ShoppingCart/OptionalFeatures.vb
> +        Return list.OrderBy(Function(i) i.MerchandisePrice).ToList
[nits] `i`って変数名やだなあ。多分`i`ってfor文に主に使われるから`index`のことだと思うんですけど

・・・この話前もしたっけ

2023-03-17 01:57 UTC, Takatatsu9 commented on ShoppingCart/InputValueValidator.vb
> +        ElseIf inputOption(0).Equals("list") AndAlso inputOption.Length = INPUT_VALUE_LENGTH And input.Contains("--sort price") Then
[Q] これ絶対通るはずがない条件だと思うんですが、通りました？

2023-03-17 01:57 UTC, Takatatsu9 commented on ShoppingCart/InputValueValidator.vb
> +            masserge = "もしかして：list --help"
マッセージ

2023-03-17 02:16 UTC, Takatatsu9 commented on ShoppingCart/MerchandiseList.vb
> +            New Merchandise("applewatch", "中古", 11000, 2)
モノけしってなんですか？
「そこ」はなんで平仮名なんですか？
Apple Watchが全部小文字なの気になるなぁ。
これら提示仕様通りですけど、疑問浮かびませんでした？
違和感持ちませんでした？改善しようとか思いませんでした？

2023-03-20 04:08 UTC, kitazawasyogo commented on ShoppingCart/InputValueValidator.vb
> +        ElseIf inputOption(0).Equals("list") AndAlso inputOption.Length = INPUT_VALUE_LENGTH And input.Contains("--sort price") Then
理解してます。
Andは複数の条件を全て判定してから処理を進め、AndAlsoは、1つ目の条件が当てはまらない時に次の条件を見ずに当てはまらなければFalseと判断して処理を進める違いがあります。

一つ目の条件の、`空白で切り分けた文字列の一番初めの文字列がlist`がTrueでなければそれ以外の条件は判定する必要がなかったのでAndalsoを使用しました。
ですが2つ目以降の条件も同じようにAndではなくAndalsoで良かったと思います。
Andalsoに変更いたします。

2023-03-20 04:09 UTC, kitazawasyogo commented on ShoppingCart/OptionalFeatures.vb
> +    Public Function RemoveByName(searchName As String, list As List(Of Merchandise)) As List(Of Merchandise)
ご指摘ありがとうございます。
「検索する」でメソッド名つけた方が適切だと思います。

コメント：名前の曖昧一致検索
メソッド名：SearchByName

コメント名：価格の範囲検索
メソッド名：SearchByPrice
に変更いたします。

2023-03-20 04:09 UTC, kitazawasyogo commented on ShoppingCart/MerchandiseList.vb
> +    Private ReadOnly nameItem As String = "商品名"
書き換える予定はありません。

書き換えない値ですので、定数にいたします。

2023-03-20 04:09 UTC, kitazawasyogo commented on ShoppingCart/InputValueValidator.vb
> +        ElseIf inputOption(0).Equals("list") AndAlso inputOption.Length = INPUT_VALUE_LENGTH And input.Contains("--sort price") Then
`list waaa----sort price`や`list --sort priceeeee`でもサジェスト表示されてしまいます。

> ただし、頭2文字が一致している場合はBashのように「もしかして: コマンド名」などサジェストを表示してほしいです。

仕様に従えていませんでした。失礼いたしました。
頭2文字が一致している場合にサジェスト表示するように修正いたします。

2023-03-20 04:25 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +        ElseIf inputOption(0).Equals("list") AndAlso inputOption.Length = INPUT_VALUE_LENGTH And input.Contains("--sort price") Then
理解の通りです。
一見、`AndAlso`で良い所を`And`使っていたので、確認しました。
なんで混ざりこんでしまったんです？理解が正しいのであれば、プロセスが問題あるはず。

2023-03-20 05:30 UTC, Takatatsu9 commented on ShoppingCart/InputValueValidator.vb
> +        ElseIf inputOption(0).Equals("list") AndAlso inputOption.Length = INPUT_VALUE_LENGTH And input.Contains("--sort price") Then
え？サジェスト表示されるんですか？
私が確認したときはサジェストではなく正常なコマンドとして動作しましたけど？

2023-03-22 01:52 UTC, kitazawasyogo commented on ShoppingCart/InputValueValidator.vb
> +        ElseIf inputOption(0).Contains("he") Then
仕様に従えていませんでした。
失礼いたしました。
頭文字2文字が一致している場合にサジェスト表示するように修正いたします。

2023-03-22 02:01 UTC, kitazawasyogo commented on ShoppingCart/InputValueValidator.vb
> +        ElseIf inputOption(0).Equals("list") AndAlso inputOption.Length = INPUT_VALUE_LENGTH And input.Contains("--sort price") Then
サジェスト表示ではなく正常なコマンドとして判定されてしまいます。
サジェスト機能に問題があり動作確認した内容と混乱してしまいました。

昇順に並び替える機能のコマンドで、`--sort price`が含まれていれば、余計な文字が含まれていても正常な機能と判定されてしまうので`list --sort price`コマンドが完全一致している場合のみ正常なコマンドとみなすように修正いたします。
名前の昇順に並び替えるコマンドの判定も同じように修正いたします。

2023-03-22 02:01 UTC, kitazawasyogo commented on ShoppingCart.Test/InputValueValidatorTest.vb
> +        Catch expected As ArgumentException
必ず例外が発生するようにして確認した結果、例外を投げない事を確認するテストのはずですが全てのTestCaseでpassedになります。

Assert.Pass（）について調べ修正いたします。

2023-03-22 02:14 UTC, nabemasamasa commented on ShoppingCart.Test/InputValueValidatorTest.vb
> +        Catch expected As ArgumentException
誤った方向にいきそうなので、軌道修正の為、即レスします。
Assert.Passは問題じゃないです。
このテストコードが問題なので、検証していただいた結果例外が発生してもpassedになっちゃってます。

「例外発生しない」ならTryCatchする意味ないです(これはちゃんと理解できてるか回答がほしい。なぜ意味がないのか)し、
そもそもこのコードだとSelectFeaturesで例外発生したらAssert.Passを通らないですし、
もしTryCatchするなら例外Catchしちゃったらテスト失敗させるべきではと思います。

2023-03-22 02:41 UTC, nabemasamasa commented on ShoppingCart.Test/InputValueValidatorTest.vb
> +        Catch expected As ArgumentException
SelectFeaturesにブレークポイントおいて、デバッグ実行すれば、ArgumentExceptionが発生した時にAssert.Passを通ってないのはすぐわかるはず。

2023-03-22 04:40 UTC, kitazawasyogo commented on ShoppingCart.Test/InputValueValidatorTest.vb
> +        Catch expected As ArgumentException
> 「例外発生しない」ならTryCatchする意味ないです(これはちゃんと理解できてるか回答がほしい。なぜ意味がないのか)し、

「今回例外が発生しない」ことをテストしたいのでtryCatchする必要がない(Tryの中の処理で例外が発生した場合にCatchの処理が行われるが処理が通るはずがない)という理解で正しいでしょうか。

「例外を投げない」テスト以下に修正いたします。

 ```
 vluseTest.SelectFeatures(inputTestValue)

Assert.Pass()
```

2023-03-22 04:55 UTC, nabemasamasa commented on ShoppingCart.Test/InputValueValidatorTest.vb
> +        Catch expected As ArgumentException
「通るはずがない」はその通りです。
[Q] SelectFeaturesで必ず例外にした時、TryCatchなしだとどうなりますか？

2023-03-22 05:33 UTC, kitazawasyogo commented on ShoppingCart.Test/InputValueValidatorTest.vb
> +        Catch expected As ArgumentException
それぞれのTestCaseで「値が有効な範囲にありません。」となり、テスト結果`5 failed`となります。

SelectFeaturesを必ず例外発生させるメソッドに変更しない場合はテスト結果`5 passed`です。

2023-03-22 05:54 UTC, nabemasamasa commented on ShoppingCart.Test/InputValueValidatorTest.vb
> +        Catch expected As ArgumentException
ありがとうございます。
まず、別解として、「例外発生しないテスト」だからCatchは通るはずがない…のでCatchの中に`Assert.Fail`を書く書き方も出来ます。
```vb
Try
  sut.SelectFeature(value)
Cactch e As ArgumentException
  '例外発生しないテストだから通らないはず。Failでコケさせる
   Assert.Fail()
End Try
```

そういう別解もあるんですが、、、、、
検証いただいたとおり、TryCatchがない時にSelectFeaturesが間違って「例外が発生しないテスト」なのに例外発生するようになってしまったとしても、ちゃんとテストがFailedになってくれます。
なので、そもそもTryCatchで囲う必要ないです、例外発生したらコケてくれるので。

2023-03-22 05:55 UTC, nabemasamasa commented on ShoppingCart.Test/InputValueValidatorTest.vb
> +
コメント書いてて気づいた。
[Q] これ、例外発生するはずなのに例外発生しなかった場合、テスト通っちゃいませんか？

2023-03-23 00:36 UTC, kitazawasyogo commented on ShoppingCart.Test/InputValueValidatorTest.vb
> +
ご指摘ありがとうございます。
`Assert.Fail()`
「例外を想定してるのに起こってなければテストはコケるべき」処理が抜けてしまっていました。
追加いたします。

2023-03-23 00:41 UTC, Takatatsu9 commented on ShoppingCart/MerchandiseList.vb
> +            New Merchandise("applewatch", "中古", 11000, 2)
返事がないので、疑問は浮かばなかったし違和感も持たなかったし改善しようとも思わなかったということで了解しました。

2023-03-23 00:52 UTC, kitazawasyogo commented on ShoppingCart/MerchandiseList.vb
> +            New Merchandise("applewatch", "中古", 11000, 2)
返信が遅くなり申し訳ありません。

提示仕様に従えていれば良い。と考えており疑問を持ちませんでした。
良くない考えで改善するべきだと思います。
提示された仕様が必ず正しいと決めつけず、疑問や違和感があれば確認いたします。

今回はIssueで仕様を握る回答者に疑問に思う部分について確認いたします。

2023-03-23 00:58 UTC, Takatatsu9 commented on ShoppingCart/MerchandiseList.vb
> +            New Merchandise("applewatch", "中古", 11000, 2)
言われたことしかしないならば今流行のAIのほうがよっぽど優秀です。
しかも毎月数十万かかる人間よりはるかに安いし。
人に出来てAIに出来ないのはそのあたりの不自然な点、不便な点を見つけて改善の提案ができることですね。

2023-03-24 02:43 UTC, nabemasamasa commented
#4 がマージされたから、最新masterでRebaseしてPushすればテストコケてるのも、解決されるはず

2023-03-28 01:23 UTC, kitazawasyogo commented
https://github.com/kitazawasyogo/shopping-cart/pull/4 テストこけてしまう問題を対応したPRマージしたので、最新masterに基点変更後に強制プッシュしました。

この後にこちらのPRでレビュー頂いた部分の修正コミットをPushいたします。

https://github.com/kitazawasyogo/shopping-cart/pull/2#issuecomment-1472978985
テストコケてるのに、MergePullRequestボタンが有効になってしまっている問題も対応済みです。

2023-03-28 01:30 UTC, nabemasamasa commented
……結果として既にレビュー済みですがテストコケちゃってますね。
レビュー指摘修正よりも、テスト修正を最優先でお願いします。
(コケたテストよく確認してないけど、もしローカルでは動いてたなら、GitHubはen-usで並び替え、ローカルだとja-jpで並び替える、環境差が原因？)

2023-03-28 04:35 UTC, nabemasamasa requested changes, later dismissed
根本解決じゃない。

2023-03-28 04:35 UTC, nabemasamasa commented on ShoppingCart.Test/OptionalFeaturesTest.vb
> -            New Merchandise("充電器", "タイプCの充電器", 2000, 10),
一目見てNG。
[Q] https://github.com/kitazawasyogo/shopping-cart/pull/2#issuecomment-1486079475 を見て、何を試しましたか？

2023-03-28 05:57 UTC, nabemasamasa commented on ShoppingCart.Test/OptionalFeaturesTest.vb
> -            New Merchandise("充電器", "タイプCの充電器", 2000, 10),
ペアプロして、テストコードを修正する「臭い物に蓋をする」修正ではなく、
ローカライゼーションに関わらず常に同じ並び替えが出来るよう、プロダクトコードを修正しました。
後は、あるべき姿へのPush待ちです。

2023-03-28 06:35 UTC, kitazawasyogo commented on ShoppingCart.Test/OptionalFeaturesTest.vb
> -            New Merchandise("充電器", "タイプCの充電器", 2000, 10),
不明点を確認せず解決しないまま対応してしまいました。
　失礼いたしました。

「環境に左右されず同じ並び替えが出来る」適切な対応のコミットを強制プッシュしました。

2023-03-30 00:06 UTC, kitazawasyogo commented
レビューありがとうございます。

ご指摘頂いた部分のコードの修正を行いました。
お忙しいところ恐縮ですがレビューお願いいたします。

2023-03-30 01:03 UTC, kitazawasyogo commented on ShoppingCart.Test/InputValueValidatorTest.vb
> +        Catch expected As ArgumentException
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/f700ed9ab1b91c4a56c91ba4457dcd21671915f1

2023-03-30 01:03 UTC, kitazawasyogo commented on ShoppingCart/MerchandiseList.vb
> +        Console.Write($"{stockItem}")
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/476cd3075a44815de1efb4ff06ea183841b8e373

2023-03-30 01:04 UTC, kitazawasyogo commented on ShoppingCart.Test/OptionalFeaturesTest.vb
> +    Public Sub 商品名で検索した商品の情報を返すか(searchName As String)
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/6fc6660ed7dacbcaa129f73c971600808460c6e5

2023-03-30 01:04 UTC, kitazawasyogo commented on ShoppingCart/OptionalFeatures.vb
> +    Public Function RemoveByName(searchName As String, list As List(Of Merchandise)) As List(Of Merchandise)
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/dd6bfd98832d746b9f1b730fa5b32cc895aa7f4e
　　　　　　　　　　　　　　：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/c9b4d13dcfc02e25d582387256845bd7526ca5f7

2023-03-30 01:04 UTC, kitazawasyogo commented on ShoppingCart.Test/OptionalFeaturesTest.vb
> +    <Test()> Public Sub 価格の範囲で検索した商品の情報を返すか()
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/8dedcb5a5f140b4cad6dba5285719a55b0f45d9b

2023-03-30 01:04 UTC, kitazawasyogo commented on ShoppingCart.Test/OptionalFeaturesTest.vb
> +    <Test()> Public Sub 価格の範囲で検索した商品の情報を返すか()
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/261aeda429241c545b343ca864ca9558aa64e7e0

価格の入力値をチェックするメソッドとテストの追加を行いました。

2023-03-30 01:04 UTC, kitazawasyogo commented on ShoppingCart.Test/OptionalFeaturesTest.vb
> +        Assert.That(actual, [Is].EqualTo(("--name 名前:商品名の曖昧一致検索を行えます。" & vbCrLf & "--price 価格-価格:指定した価格内に収まる商品の検索を行えます。" & vbCrLf & "--sort name:商品一覧を商品名の昇順に並び替える事が出来ます。" & vbCrLf & "--sort price:商品一
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/930c51affb707ad1e11359ee1eca55b39dd8d2ee

2023-03-30 01:04 UTC, kitazawasyogo commented on ShoppingCart/OptionalFeatures.vb
> +            displayHelpMessage = "--name 名前:商品名の曖昧一致検索を行えます。" & vbCrLf & "--price 価格-価格:指定した価格内に収まる商品の検索を行えます。" & vbCrLf & "--sort name:商品一覧を商品名の昇順に並び替える事が出来ます。" & vbCrLf & "--sort price:商品一覧を価格の昇順に並
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/3160f8ab1e5f73b113a451bb3afe0b638324ea39

2023-03-30 01:04 UTC, kitazawasyogo commented on ShoppingCart/OptionalFeatures.vb
> +            displayHelpMessage = "--name 名前:商品名の曖昧一致検索を行えます。" & vbCrLf & "--price 価格-価格:指定した価格内に収まる商品の検索を行えます。" & vbCrLf & "--sort name:商品一覧を商品名の昇順に並び替える事が出来ます。" & vbCrLf & "--sort price:商品一覧を価格の昇順に並
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/930c51affb707ad1e11359ee1eca55b39dd8d2ee

2023-03-30 01:04 UTC, kitazawasyogo commented on ShoppingCart/InputValueValidator.vb
> +            masserge = "もしかして：list --help"
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/06ad13a392748f039db6c875629bc63f3f765095

2023-03-30 01:04 UTC, kitazawasyogo commented on ShoppingCart/InputValueValidator.vb
> +        ElseIf inputOption(0).Equals("list") AndAlso inputOption(1).Contains("na") Then
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/dab9f802e2fbe1c8f628862b2164105b8a322b6d

2023-03-30 01:04 UTC, kitazawasyogo commented on ShoppingCart/InputValueValidator.vb
> +        ElseIf inputOption(0).Contains("he") Then
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/227fd8700d35ba0508a24f3a0f55fbe30eeb44fa

2023-03-30 01:04 UTC, kitazawasyogo commented on ShoppingCart/InputValueValidator.vb
> +            masserge = "もしかして：list --price 価格-価格"
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/574b3ef1b271a21c9ea3c67205a11a126001c4c2

2023-03-30 01:04 UTC, kitazawasyogo commented on ShoppingCart/MerchandiseList.vb
> +    Private ReadOnly nameItem As String = "商品名"
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/c842475e0b06117aaf7718cbbb08e79196f7ba69

2023-03-30 01:05 UTC, kitazawasyogo commented on ShoppingCart/OptionalFeatures.vb
> +        Return list.OrderBy(Function(i) i.MerchandisePrice).ToList
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/4d55d62b01f0ce3307907a24bd704e8433a6f5f4
　　　　　　　　　　　　　　：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/81b9f2c69799bc4fbbce13ac957ef8bdbfd04691

2023-03-30 01:05 UTC, kitazawasyogo commented on ShoppingCart/InputValueValidator.vb
> +        ElseIf inputOption(0).Equals("list") AndAlso inputOption.Length = INPUT_VALUE_LENGTH And input.Contains("--sort price") Then
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/faf28a82f5644e0658c6b8b17bd1af9e3672f532
　　　　　　　　　　　　　　：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/3d31d10945115db0afec3d9b7a67c2b5161a81d4

2023-03-30 01:05 UTC, kitazawasyogo commented on ShoppingCart/MerchandiseList.vb
> +            New Merchandise("applewatch", "中古", 11000, 2)
ご指摘ありがとうございます。

仕様について確認を行い、文言の修正が必要な箇所の修正を行いました。
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/0c86db0d2b1fac86385ff1fb2106570837fa7a41

2023-03-30 01:05 UTC, kitazawasyogo commented on ShoppingCart.Test/InputValueValidatorTest.vb
> +
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/f700ed9ab1b91c4a56c91ba4457dcd21671915f1

2023-03-30 01:15 UTC, nabemasamasa reviewed
Done

2023-03-30 01:15 UTC, nabemasamasa commented on ShoppingCart/MerchandiseList.vb
> +    Private Shared ReadOnly NAME_ITEM As String = "商品名"
[nits] StringならConstが使えます。
他に、Constが使えるのはIntegerとかLongとかShortとかDateとか、、、、
単純な値保持するような型で非Nullableなら、Constが使える可能性大

2023-03-30 01:15 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +            ElseIf inputOption(0).Equals("list") AndAlso inputOption(1).Contains("na") Then
……既に`inputOption(0).Equals("list")`の条件でネストされてるなら、このAndAlsoの`inputOption(0).Equals("list")`はいらない
AndAlsoで **毎回** 指定してる箇所をネストしちゃえば、省略できる、と伝えたかったです。

2023-03-30 01:15 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +                Return Nothing
なぜかElseの中がインデントされてる…… dab9f802e2fbe1c8f628862b2164105b8a322b6d

2023-03-30 01:15 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +            ElseIf inputOption(0).Equals("list") AndAlso inputOption(1).Contains("na") Then
と思ってたら 227fd8700d35ba0508a24f3a0f55fbe30eeb44fa で修正されてた……。

2023-03-30 01:15 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +            If inputOption(1).Substring(0, 2).Equals("he") Then
[imo] `inputOption(1).Substring(0, 2)` 意味のある変数名で変数に抽出すると首が回りやすそう。

2023-03-30 01:15 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +                Return Nothing
直後のコミットで直った…… 227fd8700d35ba0508a24f3a0f55fbe30eeb44fa

2023-03-30 01:15 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +        ElseIf inputOption(0).Equals("list") AndAlso inputOption.Length = INPUT_VALUE_LENGTH Then
[nits] 私なら`INPUT_VALUE_LENGTH`の定数名は「listコマンドで要求する引数の長さ」という事で「REQUIRE_PARAM_LENGTH_LIST_COMMAND」とかにするかな……。
`nits`だからやるかどうかは、お任せです。

以下、どうしてそういう定数名にするといいのか、というWhyです。
慣例として「要求する」「必要とする」とかで「Require」をプログラムではよく使うので、(Node.jsやPHP...)、要求引数長で「REQUIRE_PARAM_LENGTH」にしてます。
末尾「LIST_COMMAND」でコマンドまで指定しているのは、今後他のコマンドが追加された時もひょっとすると引数の長さを求めることがありそう、という「予測」があって、
末尾変えた「REQUIRE_PARAM_LENGTH_XXXXX_COMMAND」を作ればよいようにしてます。
今後他の方や未来の自分が機能追加する際に定数名で悩まなくても良いようにする狙いで、そこまで定数名に含めてます。
(いわゆる、これはこうした方が後々良いだろうな、という経験則です)

2023-03-30 01:15 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +        If Not New Regex("^[0-9]+$").IsMatch(inputValue) OrElse Not priceRange.Length = 2 OrElse priceRange(0).Equals(String.Empty) OrElse priceRange(1).Equals(String.Empty) OrElse Not Integer.Parse(
……見づらい……適宜改行を挟みたい……。

2023-03-30 01:15 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +        If Not New Regex("^[0-9]+$").IsMatch(inputValue) OrElse Not priceRange.Length = 2 OrElse priceRange(0).Equals(String.Empty) OrElse priceRange(1).Equals(String.Empty) OrElse Not Integer.Parse(
正規表現をちょっと工夫すれば、長さとか空文字かどうか、は省略できそう。「`1文字以上の整数`-`1文字以上の整数`」で正規表現のパターンを指定する……とか。
もしくは、Integer.TryParseで整数型に変換できるかどうかでも良いと思う。(`-`でSplitしてるなら負の値は入らないだろうし…)

2023-03-30 01:15 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> -            If input.Contains("--sort price") Then
なんでここコードを削除する差分が……。

2023-03-30 01:15 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> -            If input.Contains("--sort price") Then
と、思ってたら faf28a82f5644e0658c6b8b17bd1af9e3672f532 で追加差分が、、、
うぅ、いちいちここに戻ってきて変更前のコードを見て、コミット内容と一致してるかどうか、問題ないか、レビューするのがつらい……手間を強いられるのがつらい…………。

2023-03-30 01:15 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +            ElseIf inputOption(1).Equals("--sort") AndAlso inputOption(2).Equals("name") Then
結局、最終的に「並び替え」する項目が「商品名」と「価格」しかないから今はIfの条件に毎回`--sort`してもいいけど、「管理する項目を増やしたい！」とか要望が来るかも…を見据えると、Ifで囲っちゃっていいとは思う。
あくまで「かもしれない」だけどね。

2023-03-30 01:20 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +        ElseIf inputOption(0).Equals("list") AndAlso inputOption(1).Contains("na") Then
(ほんとは **毎回** `inputOption(0).Equals("list")` してる問題は 227fd8700d35ba0508a24f3a0f55fbe30eeb44fa で解決してて、dab9f80 はただネストしただけなんだよな……結果的には解決してるんだけど)

2023-03-30 01:28 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +        product.DisplayMerchandiseList(productList)
例えば、機能をテスト環境とか動作確認環境へ適用した時、お客様からの「確認に時間が掛かるから一旦除外したいです」に応えたい時に該当の機能追加コミットをRevertしたりして解決する事もあるんだけど、こんな風に「後から解決される」系のコミットが混じると、おかしくなるんだよね……。
例えば、 https://github.com/kitazawasyogo/shopping-cart/pull/2#discussion_r1152632935 で指摘した、途中デグレしてるけど後のコミットで直るパターンとかされてるとおかしくなるから、そういう「痛い目」を見ないように１コミット丁寧に差分を作っていきたい……。

「痛い目」を見て釈明に胃を痛ませないと、必要性を痛感しないのもそうなんですが……。

2023-03-30 01:34 UTC, nabemasamasa commented on ShoppingCart/MerchandiseList.vb
> +        Console.Write($"{stockItem}")
( #1 の https://github.com/kitazawasyogo/shopping-cart/issues/1#issuecomment-1459470972 のコメントの中で「半角スペースで横幅を整えてください。」と仕様について回答してあるんだけど、たぶん伝わってない気がするな……)

2023-03-30 01:36 UTC, nabemasamasa commented
やっぱり`[imo]`や`[nits]`などの指摘コメントに「修正したコミットはこちら `${ハッシュ値}` 」があるとResolveConvesationを押してよいか判断しやすくていいな……。
そしてResolveConvesationで畳んでないのがあればまだ未解決・未回答があるってわかりやすい……。

2023-03-30 06:08 UTC, kitazawasyogo commented on ShoppingCart/InputValueValidator.vb
> +        If Not New Regex("^[0-9]+$").IsMatch(inputValue) OrElse Not priceRange.Length = 2 OrElse priceRange(0).Equals(String.Empty) OrElse priceRange(1).Equals(String.Empty) OrElse Not Integer.Parse(
ご指摘ありがとうございます。
以下のように正規表現を使用してパターンの指定する方法に変更いたします。
Unitテスト動いているのでコードに問題ないかと思っています。


```
Const REQUIRE_PARAM_LENGTH_PRICE_RANGE As Integer = 2

 If Not New Regex("[0-9]\d{1,}\-[0-9]\d{1,}$").IsMatch(input) OrElse Not priceRange.Length = REQUIRE_PARAM_LENGTH_PRICE_RANGE Then
            Throw New ArgumentException("入力内容が正しくありません。")
End If
```

定数名には「価格の範囲指定で要求する引数の長さ」`REQUIRE_PARAM_LENGTH_PRICE_RANGE`にしています。
`REQUIRE_PARAM_LENGTH`だけでも良いと思いますが、後から定数を追加する時を考えて「価格の範囲」を末尾に追加しました。

2023-03-30 07:21 UTC, kitazawasyogo commented
レビューありがとうございます。

ご指摘頂いた部分のコードの修正を行いましたので、お忙しいところ恐縮ですがレビューお願いいたします。

2023-03-30 07:21 UTC, kitazawasyogo commented on ShoppingCart/InputValueValidator.vb
> +        If Not New Regex("^[0-9]+$").IsMatch(inputValue) OrElse Not priceRange.Length = 2 OrElse priceRange(0).Equals(String.Empty) OrElse priceRange(1).Equals(String.Empty) OrElse Not Integer.Parse(
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/51c57bbeb52505baeb273720fec19909c8ea66ac

2023-03-30 07:21 UTC, kitazawasyogo commented on ShoppingCart/InputValueValidator.vb
> +        ElseIf inputOption(0).Equals("list") AndAlso inputOption.Length = INPUT_VALUE_LENGTH Then
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/dbb55cfc2db1e8b5fd5e567323b9b46157320724

2023-03-30 07:21 UTC, kitazawasyogo commented on ShoppingCart/InputValueValidator.vb
> +            If inputOption(1).Substring(0, 2).Equals("he") Then
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/29502694978292b4cdf9e4b3127ef3c135d44a90

2023-03-30 07:21 UTC, kitazawasyogo commented on ShoppingCart/MerchandiseList.vb
> +    Private Shared ReadOnly NAME_ITEM As String = "商品名"
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/48b7f38d5d115cc9a5263fa9553c1affcdb8ad18

2023-03-30 07:51 UTC, nabemasamasa reviewed
done

2023-03-30 07:51 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +        Dim commandSuggestJudgment As String = inputOption(0).Substring(0, 2)
[Q] これ、コマンドが1文字だけしか入力されてなかった時、エラーになったりはしませんか？

2023-03-30 23:54 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +        If Not New Regex("^[0-9]+$").IsMatch(inputValue) OrElse Not priceRange.Length = 2 OrElse priceRange(0).Equals(String.Empty) OrElse priceRange(1).Equals(String.Empty) OrElse Not Integer.Parse(
51c57bbeb52505baeb273720fec19909c8ea66ac で条件が減って改行しなくても判別できる量になった

2023-03-31 01:05 UTC, kitazawasyogo commented on ShoppingCart/InputValueValidator.vb
> +        Dim commandSuggestJudgment As String = inputOption(0).Substring(0, 2)
`Substring(0, 2)`で2文字切り取るはずが2文字未満（0，1）の場合エラーになってしまいます。
```
インデックスおよび長さは文字列内の場所を参照しなければなりません。
パラメーター名:length
```
以下の処理を追加いたします。
If inputValue.Length < 2 Then
            Return Nothing
End If

2023-03-31 01:08 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +        Dim commandSuggestJudgment As String = inputOption(0).Substring(0, 2)
やっぱりエラーが起こっちゃうんですね…
実行したら入らないとか、レビュー時に見えてない差分のおかげで入らないとかなく…。

`Left`を使うのはいかがでしょうか？

2023-03-31 01:24 UTC, kitazawasyogo commented on ShoppingCart/InputValueValidator.vb
> +        Dim commandSuggestJudgment As String = inputOption(0).Substring(0, 2)
`Dim commandSuggestJudgment As String = Strings.Left(inputOption(0), 2)`
`Left`使用する方法にいたします。
（コード短い。長さチェックのIF文だとメソッドとして分けてテスト追加,,,が必要になってきそう）
`list --n`,`list --`も同じ内容のエラーになってしまうので修正いたします。

2023-03-31 01:35 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +        Dim commandSuggestJudgment As String = inputOption(0).Substring(0, 2)
ちなみに、このLeft(末尾から数文字取り出したいならRight)はVB.NETの前身VB時代からでサポートしているのでVBAでも使えます。
なんならSQLServerでも使えるので、覚えとくと便利です。(C#では使えないんだけどね…)

ただ、SQLServerの場合、Leftで取り出した結果はTrim(LTrimとかRTrim)しとかないと、文字数で空白埋めされてたようなしなかったような……ここは使う時とか勉強の一環で試してみてください。
戻り値が固定長(桁数に満たないと末尾空白埋めされる)のChar型だった気がするので…(varcharなら可変長だから値分だけ保持してくれるんだけど…)

2023-03-31 01:50 UTC, kitazawasyogo commented
レビューありがとうございます。

ご指摘頂いたエラーが起こってしまう部分の対応を行いました。
レビューお願いいたします。

2023-03-31 01:50 UTC, kitazawasyogo commented on ShoppingCart/InputValueValidator.vb
> +        Dim commandSuggestJudgment As String = inputOption(0).Substring(0, 2)
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/7cb08c57433f224d6185d092211a8bd5ddec943c

2023-03-31 01:58 UTC, nabemasamasa reviewed
Done

2023-03-31 02:00 UTC, nabemasamasa commented on ShoppingCart/InputValueValidator.vb
> +            Dim optionSuggestJudgment As String = Strings.Left(inputOption(1), 2)
[imo] (忘れてた)テスト欲しいです。

2023-03-31 02:38 UTC, kitazawasyogo commented
テストが不足していた為追加いたしました。
レビューお願いいたします。

2023-03-31 02:38 UTC, kitazawasyogo commented on ShoppingCart/InputValueValidator.vb
> +            Dim optionSuggestJudgment As String = Strings.Left(inputOption(1), 2)
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/47e7f9f9c16567cab9767a8c7e08e33437876ecb

2023-03-31 02:59 UTC, nabemasamasa reviewed
Done

2023-03-31 02:59 UTC, nabemasamasa commented on ShoppingCart.Test/InputValueValidatorTest.vb
> +    Public Sub コマンド入力値が2文字未満の場合nullを返す(ininputTestValue As String)
[Q] …………気づくのが遅くなってしまいましたが、`ininputTestValue`ってなんでしょうか……
`inputTestValue`が「入力テスト値」を表現したいのはわかるんですが……

2023-03-31 05:35 UTC, kitazawasyogo commented on ShoppingCart.Test/InputValueValidatorTest.vb
> +    Public Sub コマンド入力値が2文字未満の場合nullを返す(ininputTestValue As String)
「ユーザー入力値のテスト用の値」という意味をイメージして命名しましたが、、
`testValue`「テスト値」の方が適切でしょうか？

2023-03-31 05:41 UTC, nabemasamasa commented on ShoppingCart.Test/InputValueValidatorTest.vb
> +    Public Sub コマンド入力値が2文字未満の場合nullを返す(ininputTestValue As String)
いえ、**in** inputTestValue と、`input`の前に`in`が入っていることについて、質問しています。
`inputTestValue`なら既にちらほら見てて「入力した時のテスト値」でパッと見すぐわかるのでいいと思ったんですが、
この`ininputTestValue`について、キャメルケースなら`In Input Test Value`で`inInputTestValue`だし、`ininput`という単語があるのか……と。

2023-03-31 05:46 UTC, kitazawasyogo commented on ShoppingCart.Test/InputValueValidatorTest.vb
> +    Public Sub コマンド入力値が2文字未満の場合nullを返す(ininputTestValue As String)
ミスです。失礼しました。
頭の`in`は意図していないものです。

修正いたします。

2023-03-31 05:48 UTC, nabemasamasa commented on ShoppingCart.Test/InputValueValidatorTest.vb
> +    Public Sub コマンド入力値が2文字未満の場合nullを返す(ininputTestValue As String)
ｱｯﾊｲ、了解です。修正お願いします。

2023-03-31 06:00 UTC, kitazawasyogo commented
レビューありがとうございます。
ご指摘頂いた部分の修正を行いましたのでレビューお願いいたします。

2023-03-31 06:01 UTC, kitazawasyogo commented on ShoppingCart.Test/InputValueValidatorTest.vb
> +    Public Sub コマンド入力値が2文字未満の場合nullを返す(ininputTestValue As String)
対応したコミットはこちらです：https://github.com/kitazawasyogo/shopping-cart/pull/2/commits/16d43cd3d21e84d055238dcb3ccb46d1a8bfc6bf

2023-03-31 06:20 UTC, nabemasamasa reviewed
Done!

2023-03-31 06:36 UTC, kitazawasyogo commented
レビューありがとうございます。
[Takatatsu9](https://github.com/Takatatsu9)　さん不在ですがコミット整理してしまってよろしいのでしょうか？

2023-03-31 06:38 UTC, nabemasamasa commented
コミット整理してOKです。不在なのは仕方がない事なので、先に進めましょう。

2023-03-31 08:13 UTC, kitazawasyogo commented
コミット整理を行い強制プッシュしました。
[変更点](https://github.com/kitazawasyogo/shopping-cart/compare/16d43cd3d21e84d055238dcb3ccb46d1a8bfc6bf..e5ff9c158df0b4aaac6d4a6adcfd7feef7236900)はございません。

マージいたします。

2023-03-31 08:13 UTC, merged